# k8s/overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host      # The only rule is at index 0
      value: app.theutility.shop # Set the correct hostname
  target:
    kind: Ingress
    name: app-main-ingress

- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: currency-converter