apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: argocd.theutility.shop
    - op: replace
      path: /spec/rules/1/host
      value: application.theutility.shop

  target:
    kind: Ingress
    name: shared-main-ingress 
    
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: currency-converter 