apiVersion: v1
kind: Service
metadata:
  name: currency-converter-service
spec:
  type: ClusterIP
  selector:
    app: currency-converter
  ports:
  - protocol: TCP
    name: http
    port: 81
    targetPort: 5555
