#NO CHANGR

apiVersion: v1
kind: Service
metadata:
  name: currency-converter-service
spec:
  type: ClusterIP
  selector:
    app: currency-converter
  ports:
  - name: http
    protocol: TCP
    port: 80 
    targetPort: 5555 